version: '3'
services:
  mysql:
    image: 'shantanu1990/mysql:latest'
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    networks:
      - twotier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  flaskapp:
    image: 'shantanu1990/flaskapp:latest'
    ports:
      - '5000:5000'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: myDb
    depends_on:
      - mysql
    networks:
      - twotier

networks:
  twotier:
    driver: bridge
