apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldata
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root/mysql-data #This is your host path where your data will be stored. Make sure to create mysqldata directory in mentioned path
